-- Fix: "Service role inserts insights" used WITH CHECK (true) which let any
-- role inject content as if it were generated by Aliis (medical misinfo vector).
-- Crons use service role which bypasses RLS.
ALTER TABLE aliis_insights ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Service role inserts insights" ON aliis_insights;
