// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiqcypomM0weA8bwsH9Vmq9vayCoxE1Jc',
    appId: '1:552582157874:web:0637f8c63ed257ce17ce2b',
    messagingSenderId: '552582157874',
    projectId: 'aliis-v0',
    authDomain: 'aliis-v0.firebaseapp.com',
    storageBucket: 'aliis-v0.firebasestorage.app',
    measurementId: 'G-CMMSNN0NGD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoeuXrGu22p0-CMUo9hIwepAIp4dkx3KA',
    appId: '1:552582157874:android:efebbdb49893447717ce2b',
    messagingSenderId: '552582157874',
    projectId: 'aliis-v0',
    storageBucket: 'aliis-v0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPR5_WBcxvGRK-rl5FNwDZDshhe6903XI',
    appId: '1:552582157874:ios:b4bc08f928411b0c17ce2b',
    messagingSenderId: '552582157874',
    projectId: 'aliis-v0',
    storageBucket: 'aliis-v0.firebasestorage.app',
    iosBundleId: 'com.example.aliisMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPR5_WBcxvGRK-rl5FNwDZDshhe6903XI',
    appId: '1:552582157874:ios:b4bc08f928411b0c17ce2b',
    messagingSenderId: '552582157874',
    projectId: 'aliis-v0',
    storageBucket: 'aliis-v0.firebasestorage.app',
    iosBundleId: 'com.example.aliisMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAiqcypomM0weA8bwsH9Vmq9vayCoxE1Jc',
    appId: '1:552582157874:web:629ad8350478273117ce2b',
    messagingSenderId: '552582157874',
    projectId: 'aliis-v0',
    authDomain: 'aliis-v0.firebaseapp.com',
    storageBucket: 'aliis-v0.firebasestorage.app',
    measurementId: 'G-GETGLCX4ZY',
  );
}
